### ISSUE TITLE
Unable to activate pipenv environment

### ISSUE THREAD

**Issue by Aju100** [morenoh149/interview_question_python#1]
Hello @morenoh149 From the instruction of README. 
I followed the way of installing python environment and I am not able to activate the virtual environment. Here the Error that I got that pipenv file.
-  https://paste.ubuntu.com/p/zPM3Sxtf2B/
In order to solve this issue, can i delete the old environment and activate the new environment ?
And I look the code of pipenv file. It doesn't shows the version of flask too.

**Comment by morenoh149** [comment]
Figured it out?

**Comment by Aju100** [comment]
@morenoh149  yeah I just recreated new one.
